[package]
name = "squared"
version = "0.1.0"
edition = "2021"
description = "Placeholder"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nikomatsakis/squared"
documentation = "https://nikomatsakis.github.io/squared"

[dependencies]

[workspace]
members = [
    "demos/hello_world",
    "demos/hello_world/squared/",
]