[package]
name = "lingo-star"
version = "0.1.0"
edition = "2021"
description = "Placeholder"
license = "MIT OR Apache-2.0"
repository = "https://github.com/lingo-star/lingo-star"
documentation = "https://lingo-star.github.io/lingo-star"

[lib]
proc-macro = true

[[test]]
name = "harness"
harness = false

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"


[workspace]
members = [ "crates/cargo-lingo", "crates/lingo-star-idl",
    "demos/hello_world",
    "demos/hello_world/squared/",
]

[dev-dependencies]
anyhow = "1.0.95"
lingo-star-idl = { path = "crates/lingo-star-idl" }
progress_bar = "1.0.6"
walkdir = "2.5.0"
